import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';

// const geistSans = Geist({
// 	variable: '--font-geist-sans',
// 	subsets: ['latin', 'cyrillic'],
// });

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin', 'cyrillic'],
// });

const inter = Inter({
	// weight: ['400', '500', '700'], // Какие начертания нужны
	subsets: ['latin', 'cyrillic'], // Латиница + кириллица
	display: 'swap', // Плавная загрузка
	variable: '--font-inter', // CSS переменная (опционально)
});

export const metadata: Metadata = {
	title: 'ООО «АйТиСМ» - Красноярск',
	// description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			{/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
			<body className={`${inter.variable}`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
